"""create telemetry and incident tables

Revision ID: 3e156083e716
Revises: ceba3a9a0e14
Create Date: 2026-02-24 03:43:01.353335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e156083e716'
down_revision: Union[str, Sequence[str], None] = 'ceba3a9a0e14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('senior_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('incident_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['senior_id'], ['seniors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_device_id'), 'incidents', ['device_id'], unique=False)
    op.create_index(op.f('ix_incidents_senior_id'), 'incidents', ['senior_id'], unique=False)
    op.create_table('telemetries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('metric_type', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetries_created_at'), 'telemetries', ['created_at'], unique=False)
    op.create_index(op.f('ix_telemetries_device_id'), 'telemetries', ['device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetries_device_id'), table_name='telemetries')
    op.drop_index(op.f('ix_telemetries_created_at'), table_name='telemetries')
    op.drop_table('telemetries')
    op.drop_index(op.f('ix_incidents_senior_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_device_id'), table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
