"""add escalation fields to incidents

Revision ID: a26caae9d438
Revises: 3e156083e716
Create Date: 2026-02-24 04:14:41.194404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a26caae9d438'
down_revision: Union[str, Sequence[str], None] = '3e156083e716'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add columns with nullable=True first for existing data
    op.add_column('incidents', sa.Column('escalation_minutes', sa.Integer(), nullable=True))
    op.add_column('incidents', sa.Column('escalated', sa.Boolean(), nullable=True))
    op.add_column('incidents', sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True))
    
    # Set defaults for existing rows
    op.execute("UPDATE incidents SET escalation_minutes = 15 WHERE escalation_minutes IS NULL")
    op.execute("UPDATE incidents SET escalated = false WHERE escalated IS NULL")
    
    # Now make non-nullable
    op.alter_column('incidents', 'escalation_minutes', nullable=False)
    op.alter_column('incidents', 'escalated', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'escalated_at')
    op.drop_column('incidents', 'escalated')
    op.drop_column('incidents', 'escalation_minutes')
    # ### end Alembic commands ###
